services:
  distro-kid-api:
    build:
      context: ..
      dockerfile: DistroKid.Deployment/Dockerfile
    ports:
      - "5000:5001"
    environment:
      ASPNETCORE_URLS: "http://+:5001"
      ConnectionStrings__WebAppDatabase: "Server=distro-kid-db;Port=5432;Database=distro-kid;User Id=distro-kid;Password=distro-kid;"
      MailConfiguration__MailEnable: "${MAIL_ENABLE:-false}"
      MailConfiguration__MailHost: "${MAIL_HOST:-sandbox.smtp.mailtrap.io}"
      MailConfiguration__MailPort: "${MAIL_PORT:-2525}"
      MailConfiguration__MailAddress: "${MAIL_ADDRESS:-test@my.app}"
      MailConfiguration__MailUser: "${MAIL_USER:-}"
      MailConfiguration__MailPassword: "${MAIL_PASSWORD:-}"
    depends_on:
      - distro-kid-db

  distro-kid-db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: distro-kid
      POSTGRES_DB: distro-kid
      POSTGRES_PASSWORD: distro-kid
    volumes:
      - distro-kid-db-vol:/var/lib/postgresql/data

volumes:
  distro-kid-db-vol:
