/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedbackAddRecord,
  RequestResponse,
} from '../models/index';
import {
    FeedbackAddRecordFromJSON,
    FeedbackAddRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiFeedbackAddPostRequest {
    feedbackAddRecord?: FeedbackAddRecord;
}

/**
 * 
 */
export class FeedbackApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiFeedbackAddPost without sending the request
     */
    async apiFeedbackAddPostRequestOpts(requestParameters: ApiFeedbackAddPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Feedback/Add`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FeedbackAddRecordToJSON(requestParameters['feedbackAddRecord']),
        };
    }

    /**
     */
    async apiFeedbackAddPostRaw(requestParameters: ApiFeedbackAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiFeedbackAddPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbackAddPost(requestParameters: ApiFeedbackAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiFeedbackAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
