/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PlatformAddRecord,
  PlatformRecordListRequestResponse,
  PlatformRecordRequestResponse,
  PlatformUpdateRecord,
  RequestResponse,
} from '../models/index';
import {
    PlatformAddRecordFromJSON,
    PlatformAddRecordToJSON,
    PlatformRecordListRequestResponseFromJSON,
    PlatformRecordListRequestResponseToJSON,
    PlatformRecordRequestResponseFromJSON,
    PlatformRecordRequestResponseToJSON,
    PlatformUpdateRecordFromJSON,
    PlatformUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiPlatformAddPostRequest {
    platformAddRecord?: PlatformAddRecord;
}

export interface ApiPlatformDeleteIdDeleteRequest {
    id: string;
}

export interface ApiPlatformGetByIdIdGetRequest {
    id: string;
}

export interface ApiPlatformUpdateIdPutRequest {
    id: string;
    platformUpdateRecord?: PlatformUpdateRecord;
}

/**
 * 
 */
export class PlatformApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiPlatformAddPost without sending the request
     */
    async apiPlatformAddPostRequestOpts(requestParameters: ApiPlatformAddPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Platform/Add`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlatformAddRecordToJSON(requestParameters['platformAddRecord']),
        };
    }

    /**
     */
    async apiPlatformAddPostRaw(requestParameters: ApiPlatformAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiPlatformAddPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlatformAddPost(requestParameters: ApiPlatformAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPlatformAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPlatformDeleteIdDelete without sending the request
     */
    async apiPlatformDeleteIdDeleteRequestOpts(requestParameters: ApiPlatformDeleteIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPlatformDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Platform/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiPlatformDeleteIdDeleteRaw(requestParameters: ApiPlatformDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiPlatformDeleteIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlatformDeleteIdDelete(requestParameters: ApiPlatformDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPlatformDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPlatformGetAllGet without sending the request
     */
    async apiPlatformGetAllGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Platform/GetAll`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiPlatformGetAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlatformRecordListRequestResponse>> {
        const requestOptions = await this.apiPlatformGetAllGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlatformRecordListRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlatformGetAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlatformRecordListRequestResponse> {
        const response = await this.apiPlatformGetAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPlatformGetByIdIdGet without sending the request
     */
    async apiPlatformGetByIdIdGetRequestOpts(requestParameters: ApiPlatformGetByIdIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPlatformGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Platform/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiPlatformGetByIdIdGetRaw(requestParameters: ApiPlatformGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlatformRecordRequestResponse>> {
        const requestOptions = await this.apiPlatformGetByIdIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlatformRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlatformGetByIdIdGet(requestParameters: ApiPlatformGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlatformRecordRequestResponse> {
        const response = await this.apiPlatformGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiPlatformUpdateIdPut without sending the request
     */
    async apiPlatformUpdateIdPutRequestOpts(requestParameters: ApiPlatformUpdateIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPlatformUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Platform/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlatformUpdateRecordToJSON(requestParameters['platformUpdateRecord']),
        };
    }

    /**
     */
    async apiPlatformUpdateIdPutRaw(requestParameters: ApiPlatformUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiPlatformUpdateIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiPlatformUpdateIdPut(requestParameters: ApiPlatformUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiPlatformUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
