/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReleaseAddRecord,
  ReleaseRecordPagedResponseRequestResponse,
  ReleaseRecordRequestResponse,
  ReleaseUpdateRecord,
  RequestResponse,
} from '../models/index';
import {
    ReleaseAddRecordFromJSON,
    ReleaseAddRecordToJSON,
    ReleaseRecordPagedResponseRequestResponseFromJSON,
    ReleaseRecordPagedResponseRequestResponseToJSON,
    ReleaseRecordRequestResponseFromJSON,
    ReleaseRecordRequestResponseToJSON,
    ReleaseUpdateRecordFromJSON,
    ReleaseUpdateRecordToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models/index';

export interface ApiReleaseAddPostRequest {
    releaseAddRecord?: ReleaseAddRecord;
}

export interface ApiReleaseDeleteIdDeleteRequest {
    id: string;
}

export interface ApiReleaseGetByIdIdGetRequest {
    id: string;
}

export interface ApiReleaseGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiReleaseUpdateIdPutRequest {
    id: string;
    releaseUpdateRecord?: ReleaseUpdateRecord;
}

/**
 * 
 */
export class ReleaseApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiReleaseAddPost without sending the request
     */
    async apiReleaseAddPostRequestOpts(requestParameters: ApiReleaseAddPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Release/Add`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReleaseAddRecordToJSON(requestParameters['releaseAddRecord']),
        };
    }

    /**
     */
    async apiReleaseAddPostRaw(requestParameters: ApiReleaseAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiReleaseAddPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReleaseAddPost(requestParameters: ApiReleaseAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiReleaseAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReleaseDeleteIdDelete without sending the request
     */
    async apiReleaseDeleteIdDeleteRequestOpts(requestParameters: ApiReleaseDeleteIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiReleaseDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Release/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiReleaseDeleteIdDeleteRaw(requestParameters: ApiReleaseDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiReleaseDeleteIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReleaseDeleteIdDelete(requestParameters: ApiReleaseDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiReleaseDeleteIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReleaseGetByIdIdGet without sending the request
     */
    async apiReleaseGetByIdIdGetRequestOpts(requestParameters: ApiReleaseGetByIdIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiReleaseGetByIdIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Release/GetById/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiReleaseGetByIdIdGetRaw(requestParameters: ApiReleaseGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReleaseRecordRequestResponse>> {
        const requestOptions = await this.apiReleaseGetByIdIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReleaseRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReleaseGetByIdIdGet(requestParameters: ApiReleaseGetByIdIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReleaseRecordRequestResponse> {
        const response = await this.apiReleaseGetByIdIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReleaseGetPageGet without sending the request
     */
    async apiReleaseGetPageGetRequestOpts(requestParameters: ApiReleaseGetPageGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['Search'] = requestParameters['search'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Release/GetPage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiReleaseGetPageGetRaw(requestParameters: ApiReleaseGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReleaseRecordPagedResponseRequestResponse>> {
        const requestOptions = await this.apiReleaseGetPageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReleaseRecordPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReleaseGetPageGet(requestParameters: ApiReleaseGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReleaseRecordPagedResponseRequestResponse> {
        const response = await this.apiReleaseGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiReleaseUpdateIdPut without sending the request
     */
    async apiReleaseUpdateIdPutRequestOpts(requestParameters: ApiReleaseUpdateIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiReleaseUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Release/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReleaseUpdateRecordToJSON(requestParameters['releaseUpdateRecord']),
        };
    }

    /**
     */
    async apiReleaseUpdateIdPutRaw(requestParameters: ApiReleaseUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const requestOptions = await this.apiReleaseUpdateIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiReleaseUpdateIdPut(requestParameters: ApiReleaseUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiReleaseUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
