<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NextjsStaticHosting.AspNetCore" Version="0.9.3-preview" />
  </ItemGroup>

  <Target Name="BuildNextJs" BeforeTargets="Build">
    <Message Text="Building Next.js Client..." Importance="high" />

    <Exec Command="npm install" WorkingDirectory="../DistroKid.Client" />

    <Exec Command="npm run build" WorkingDirectory="../DistroKid.Client" />

    <Message Text="Copying Next.js output to wwwroot..." Importance="high" />
    <ItemGroup>
      <NextJsOutput Include="../DistroKid.Client/out/**/*.*" />
    </ItemGroup>

    <RemoveDir Directories="wwwroot" Condition="Exists('wwwroot')" />

    <Copy SourceFiles="@(NextJsOutput)" DestinationFolder="wwwroot\%(RecursiveDir)" />
  </Target>
  
  <ItemGroup>
    <ProjectReference Include="..\DistroKid.Infrastructure\DistroKid.Infrastructure.csproj" />
    <ProjectReference Include="..\DistroKid.Services\DistroKid.Services.csproj" />
  </ItemGroup>

</Project>
