/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginRecord,
  LoginResponseRecordRequestResponse,
  RegisterRecord,
  RegisterResponseRecordRequestResponse,
} from '../models/index';
import {
    LoginRecordFromJSON,
    LoginRecordToJSON,
    LoginResponseRecordRequestResponseFromJSON,
    LoginResponseRecordRequestResponseToJSON,
    RegisterRecordFromJSON,
    RegisterRecordToJSON,
    RegisterResponseRecordRequestResponseFromJSON,
    RegisterResponseRecordRequestResponseToJSON,
} from '../models/index';

export interface ApiAuthorizationLoginPostRequest {
    loginRecord?: LoginRecord;
}

export interface ApiAuthorizationRegisterPostRequest {
    registerRecord?: RegisterRecord;
}

/**
 * 
 */
export class AuthorizationApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiAuthorizationLoginPost without sending the request
     */
    async apiAuthorizationLoginPostRequestOpts(requestParameters: ApiAuthorizationLoginPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Authorization/Login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRecordToJSON(requestParameters['loginRecord']),
        };
    }

    /**
     */
    async apiAuthorizationLoginPostRaw(requestParameters: ApiAuthorizationLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponseRecordRequestResponse>> {
        const requestOptions = await this.apiAuthorizationLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizationLoginPost(requestParameters: ApiAuthorizationLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponseRecordRequestResponse> {
        const response = await this.apiAuthorizationLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAuthorizationRegisterPost without sending the request
     */
    async apiAuthorizationRegisterPostRequestOpts(requestParameters: ApiAuthorizationRegisterPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Authorization/Register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRecordToJSON(requestParameters['registerRecord']),
        };
    }

    /**
     */
    async apiAuthorizationRegisterPostRaw(requestParameters: ApiAuthorizationRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterResponseRecordRequestResponse>> {
        const requestOptions = await this.apiAuthorizationRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterResponseRecordRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthorizationRegisterPost(requestParameters: ApiAuthorizationRegisterPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterResponseRecordRequestResponse> {
        const response = await this.apiAuthorizationRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
