/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';

/**
 * 
 * @export
 * @interface FeedbackRecord
 */
export interface FeedbackRecord {
    /**
     * 
     * @type {string}
     * @memberof FeedbackRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRecord
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackRecord
     */
    rating: number;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackRecord
     */
    isAnonymous: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedbackRecord
     */
    comment: string;
    /**
     * 
     * @type {UserRecord}
     * @memberof FeedbackRecord
     */
    user?: UserRecord | null;
}

/**
 * Check if a given object implements the FeedbackRecord interface.
 */
export function instanceOfFeedbackRecord(value: object): value is FeedbackRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('isAnonymous' in value) || value['isAnonymous'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function FeedbackRecordFromJSON(json: any): FeedbackRecord {
    return FeedbackRecordFromJSONTyped(json, false);
}

export function FeedbackRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'rating': json['rating'],
        'isAnonymous': json['isAnonymous'],
        'comment': json['comment'],
        'user': json['user'] == null ? undefined : UserRecordFromJSON(json['user']),
    };
}

export function FeedbackRecordToJSON(json: any): FeedbackRecord {
    return FeedbackRecordToJSONTyped(json, false);
}

export function FeedbackRecordToJSONTyped(value?: FeedbackRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'rating': value['rating'],
        'isAnonymous': value['isAnonymous'],
        'comment': value['comment'],
        'user': UserRecordToJSON(value['user']),
    };
}

