/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelRecordPagedResponse } from './LabelRecordPagedResponse';
import {
    LabelRecordPagedResponseFromJSON,
    LabelRecordPagedResponseFromJSONTyped,
    LabelRecordPagedResponseToJSON,
    LabelRecordPagedResponseToJSONTyped,
} from './LabelRecordPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface LabelRecordPagedResponseRequestResponse
 */
export interface LabelRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {LabelRecordPagedResponse}
     * @memberof LabelRecordPagedResponseRequestResponse
     */
    readonly response?: LabelRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LabelRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the LabelRecordPagedResponseRequestResponse interface.
 */
export function instanceOfLabelRecordPagedResponseRequestResponse(value: object): value is LabelRecordPagedResponseRequestResponse {
    return true;
}

export function LabelRecordPagedResponseRequestResponseFromJSON(json: any): LabelRecordPagedResponseRequestResponse {
    return LabelRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function LabelRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : LabelRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LabelRecordPagedResponseRequestResponseToJSON(json: any): LabelRecordPagedResponseRequestResponse {
    return LabelRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function LabelRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<LabelRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

