/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabelRecord } from './LabelRecord';
import {
    LabelRecordFromJSON,
    LabelRecordFromJSONTyped,
    LabelRecordToJSON,
    LabelRecordToJSONTyped,
} from './LabelRecord';

/**
 * 
 * @export
 * @interface LabelRecordPagedResponse
 */
export interface LabelRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof LabelRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof LabelRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof LabelRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<LabelRecord>}
     * @memberof LabelRecordPagedResponse
     */
    data: Array<LabelRecord>;
}

/**
 * Check if a given object implements the LabelRecordPagedResponse interface.
 */
export function instanceOfLabelRecordPagedResponse(value: object): value is LabelRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LabelRecordPagedResponseFromJSON(json: any): LabelRecordPagedResponse {
    return LabelRecordPagedResponseFromJSONTyped(json, false);
}

export function LabelRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(LabelRecordFromJSON)),
    };
}

export function LabelRecordPagedResponseToJSON(json: any): LabelRecordPagedResponse {
    return LabelRecordPagedResponseToJSONTyped(json, false);
}

export function LabelRecordPagedResponseToJSONTyped(value?: LabelRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(LabelRecordToJSON)),
    };
}

