/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MerchAddRecord
 */
export interface MerchAddRecord {
    /**
     * 
     * @type {string}
     * @memberof MerchAddRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MerchAddRecord
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof MerchAddRecord
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof MerchAddRecord
     */
    stock: number;
}

/**
 * Check if a given object implements the MerchAddRecord interface.
 */
export function instanceOfMerchAddRecord(value: object): value is MerchAddRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('stock' in value) || value['stock'] === undefined) return false;
    return true;
}

export function MerchAddRecordFromJSON(json: any): MerchAddRecord {
    return MerchAddRecordFromJSONTyped(json, false);
}

export function MerchAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'price': json['price'],
        'stock': json['stock'],
    };
}

export function MerchAddRecordToJSON(json: any): MerchAddRecord {
    return MerchAddRecordToJSONTyped(json, false);
}

export function MerchAddRecordToJSONTyped(value?: MerchAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'stock': value['stock'],
    };
}

