/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MerchRecordPagedResponse } from './MerchRecordPagedResponse';
import {
    MerchRecordPagedResponseFromJSON,
    MerchRecordPagedResponseFromJSONTyped,
    MerchRecordPagedResponseToJSON,
    MerchRecordPagedResponseToJSONTyped,
} from './MerchRecordPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface MerchRecordPagedResponseRequestResponse
 */
export interface MerchRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {MerchRecordPagedResponse}
     * @memberof MerchRecordPagedResponseRequestResponse
     */
    readonly response?: MerchRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MerchRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the MerchRecordPagedResponseRequestResponse interface.
 */
export function instanceOfMerchRecordPagedResponseRequestResponse(value: object): value is MerchRecordPagedResponseRequestResponse {
    return true;
}

export function MerchRecordPagedResponseRequestResponseFromJSON(json: any): MerchRecordPagedResponseRequestResponse {
    return MerchRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function MerchRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : MerchRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MerchRecordPagedResponseRequestResponseToJSON(json: any): MerchRecordPagedResponseRequestResponse {
    return MerchRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function MerchRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<MerchRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

