/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MerchRecord } from './MerchRecord';
import {
    MerchRecordFromJSON,
    MerchRecordFromJSONTyped,
    MerchRecordToJSON,
    MerchRecordToJSONTyped,
} from './MerchRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface MerchRecordRequestResponse
 */
export interface MerchRecordRequestResponse {
    /**
     * 
     * @type {MerchRecord}
     * @memberof MerchRecordRequestResponse
     */
    readonly response?: MerchRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MerchRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the MerchRecordRequestResponse interface.
 */
export function instanceOfMerchRecordRequestResponse(value: object): value is MerchRecordRequestResponse {
    return true;
}

export function MerchRecordRequestResponseFromJSON(json: any): MerchRecordRequestResponse {
    return MerchRecordRequestResponseFromJSONTyped(json, false);
}

export function MerchRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : MerchRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MerchRecordRequestResponseToJSON(json: any): MerchRecordRequestResponse {
    return MerchRecordRequestResponseToJSONTyped(json, false);
}

export function MerchRecordRequestResponseToJSONTyped(value?: Omit<MerchRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

