/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MerchRecord } from './MerchRecord';
import {
    MerchRecordFromJSON,
    MerchRecordFromJSONTyped,
    MerchRecordToJSON,
    MerchRecordToJSONTyped,
} from './MerchRecord';

/**
 * 
 * @export
 * @interface MerchRecordPagedResponse
 */
export interface MerchRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof MerchRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof MerchRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof MerchRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<MerchRecord>}
     * @memberof MerchRecordPagedResponse
     */
    data: Array<MerchRecord>;
}

/**
 * Check if a given object implements the MerchRecordPagedResponse interface.
 */
export function instanceOfMerchRecordPagedResponse(value: object): value is MerchRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MerchRecordPagedResponseFromJSON(json: any): MerchRecordPagedResponse {
    return MerchRecordPagedResponseFromJSONTyped(json, false);
}

export function MerchRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(MerchRecordFromJSON)),
    };
}

export function MerchRecordPagedResponseToJSON(json: any): MerchRecordPagedResponse {
    return MerchRecordPagedResponseToJSONTyped(json, false);
}

export function MerchRecordPagedResponseToJSONTyped(value?: MerchRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(MerchRecordToJSON)),
    };
}

