/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformRecord
 */
export interface PlatformRecord {
    /**
     * 
     * @type {string}
     * @memberof PlatformRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlatformRecord
     */
    url: string;
}

/**
 * Check if a given object implements the PlatformRecord interface.
 */
export function instanceOfPlatformRecord(value: object): value is PlatformRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PlatformRecordFromJSON(json: any): PlatformRecord {
    return PlatformRecordFromJSONTyped(json, false);
}

export function PlatformRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function PlatformRecordToJSON(json: any): PlatformRecord {
    return PlatformRecordToJSONTyped(json, false);
}

export function PlatformRecordToJSONTyped(value?: PlatformRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
    };
}

