/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformRecord } from './PlatformRecord';
import {
    PlatformRecordFromJSON,
    PlatformRecordFromJSONTyped,
    PlatformRecordToJSON,
    PlatformRecordToJSONTyped,
} from './PlatformRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface PlatformRecordRequestResponse
 */
export interface PlatformRecordRequestResponse {
    /**
     * 
     * @type {PlatformRecord}
     * @memberof PlatformRecordRequestResponse
     */
    readonly response?: PlatformRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof PlatformRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the PlatformRecordRequestResponse interface.
 */
export function instanceOfPlatformRecordRequestResponse(value: object): value is PlatformRecordRequestResponse {
    return true;
}

export function PlatformRecordRequestResponseFromJSON(json: any): PlatformRecordRequestResponse {
    return PlatformRecordRequestResponseFromJSONTyped(json, false);
}

export function PlatformRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : PlatformRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PlatformRecordRequestResponseToJSON(json: any): PlatformRecordRequestResponse {
    return PlatformRecordRequestResponseToJSONTyped(json, false);
}

export function PlatformRecordRequestResponseToJSONTyped(value?: Omit<PlatformRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

