/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
    UserRoleEnumToJSONTyped,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface RegisterRecord
 */
export interface RegisterRecord {
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    confirmPassword: string;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof RegisterRecord
     */
    role: UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterRecord
     */
    socialMediaLink?: string | null;
}



/**
 * Check if a given object implements the RegisterRecord interface.
 */
export function instanceOfRegisterRecord(value: object): value is RegisterRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirmPassword' in value) || value['confirmPassword'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function RegisterRecordFromJSON(json: any): RegisterRecord {
    return RegisterRecordFromJSONTyped(json, false);
}

export function RegisterRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
        'role': UserRoleEnumFromJSON(json['role']),
        'bio': json['bio'] == null ? undefined : json['bio'],
        'socialMediaLink': json['socialMediaLink'] == null ? undefined : json['socialMediaLink'],
    };
}

export function RegisterRecordToJSON(json: any): RegisterRecord {
    return RegisterRecordToJSONTyped(json, false);
}

export function RegisterRecordToJSONTyped(value?: RegisterRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
        'confirmPassword': value['confirmPassword'],
        'role': UserRoleEnumToJSON(value['role']),
        'bio': value['bio'],
        'socialMediaLink': value['socialMediaLink'],
    };
}

