/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReleaseTypeEnum } from './ReleaseTypeEnum';
import {
    ReleaseTypeEnumFromJSON,
    ReleaseTypeEnumFromJSONTyped,
    ReleaseTypeEnumToJSON,
    ReleaseTypeEnumToJSONTyped,
} from './ReleaseTypeEnum';

/**
 * 
 * @export
 * @interface ReleaseAddRecord
 */
export interface ReleaseAddRecord {
    /**
     * 
     * @type {string}
     * @memberof ReleaseAddRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ReleaseAddRecord
     */
    label: string;
    /**
     * 
     * @type {ReleaseTypeEnum}
     * @memberof ReleaseAddRecord
     */
    releaseType: ReleaseTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof ReleaseAddRecord
     */
    releaseDate: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReleaseAddRecord
     */
    trackIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReleaseAddRecord
     */
    platformIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ReleaseAddRecord
     */
    artistId?: string | null;
}



/**
 * Check if a given object implements the ReleaseAddRecord interface.
 */
export function instanceOfReleaseAddRecord(value: object): value is ReleaseAddRecord {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('releaseType' in value) || value['releaseType'] === undefined) return false;
    if (!('releaseDate' in value) || value['releaseDate'] === undefined) return false;
    if (!('trackIds' in value) || value['trackIds'] === undefined) return false;
    if (!('platformIds' in value) || value['platformIds'] === undefined) return false;
    return true;
}

export function ReleaseAddRecordFromJSON(json: any): ReleaseAddRecord {
    return ReleaseAddRecordFromJSONTyped(json, false);
}

export function ReleaseAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'label': json['label'],
        'releaseType': ReleaseTypeEnumFromJSON(json['releaseType']),
        'releaseDate': (new Date(json['releaseDate'])),
        'trackIds': json['trackIds'],
        'platformIds': json['platformIds'],
        'artistId': json['artistId'] == null ? undefined : json['artistId'],
    };
}

export function ReleaseAddRecordToJSON(json: any): ReleaseAddRecord {
    return ReleaseAddRecordToJSONTyped(json, false);
}

export function ReleaseAddRecordToJSONTyped(value?: ReleaseAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'label': value['label'],
        'releaseType': ReleaseTypeEnumToJSON(value['releaseType']),
        'releaseDate': value['releaseDate'].toISOString(),
        'trackIds': value['trackIds'],
        'platformIds': value['platformIds'],
        'artistId': value['artistId'],
    };
}

