/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReleaseRecordPagedResponse } from './ReleaseRecordPagedResponse';
import {
    ReleaseRecordPagedResponseFromJSON,
    ReleaseRecordPagedResponseFromJSONTyped,
    ReleaseRecordPagedResponseToJSON,
    ReleaseRecordPagedResponseToJSONTyped,
} from './ReleaseRecordPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ReleaseRecordPagedResponseRequestResponse
 */
export interface ReleaseRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {ReleaseRecordPagedResponse}
     * @memberof ReleaseRecordPagedResponseRequestResponse
     */
    readonly response?: ReleaseRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ReleaseRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ReleaseRecordPagedResponseRequestResponse interface.
 */
export function instanceOfReleaseRecordPagedResponseRequestResponse(value: object): value is ReleaseRecordPagedResponseRequestResponse {
    return true;
}

export function ReleaseRecordPagedResponseRequestResponseFromJSON(json: any): ReleaseRecordPagedResponseRequestResponse {
    return ReleaseRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ReleaseRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ReleaseRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ReleaseRecordPagedResponseRequestResponseToJSON(json: any): ReleaseRecordPagedResponseRequestResponse {
    return ReleaseRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function ReleaseRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<ReleaseRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

