/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackRecord } from './TrackRecord';
import {
    TrackRecordFromJSON,
    TrackRecordFromJSONTyped,
    TrackRecordToJSON,
    TrackRecordToJSONTyped,
} from './TrackRecord';

/**
 * 
 * @export
 * @interface TrackRecordPagedResponse
 */
export interface TrackRecordPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof TrackRecordPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof TrackRecordPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof TrackRecordPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<TrackRecord>}
     * @memberof TrackRecordPagedResponse
     */
    data: Array<TrackRecord>;
}

/**
 * Check if a given object implements the TrackRecordPagedResponse interface.
 */
export function instanceOfTrackRecordPagedResponse(value: object): value is TrackRecordPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TrackRecordPagedResponseFromJSON(json: any): TrackRecordPagedResponse {
    return TrackRecordPagedResponseFromJSONTyped(json, false);
}

export function TrackRecordPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRecordPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(TrackRecordFromJSON)),
    };
}

export function TrackRecordPagedResponseToJSON(json: any): TrackRecordPagedResponse {
    return TrackRecordPagedResponseToJSONTyped(json, false);
}

export function TrackRecordPagedResponseToJSONTyped(value?: TrackRecordPagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(TrackRecordToJSON)),
    };
}

