/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackAddRecord
 */
export interface TrackAddRecord {
    /**
     * 
     * @type {string}
     * @memberof TrackAddRecord
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof TrackAddRecord
     */
    durationInSeconds: number;
    /**
     * 
     * @type {string}
     * @memberof TrackAddRecord
     */
    isrc: string;
    /**
     * 
     * @type {string}
     * @memberof TrackAddRecord
     */
    artistId: string;
}

/**
 * Check if a given object implements the TrackAddRecord interface.
 */
export function instanceOfTrackAddRecord(value: object): value is TrackAddRecord {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('durationInSeconds' in value) || value['durationInSeconds'] === undefined) return false;
    if (!('isrc' in value) || value['isrc'] === undefined) return false;
    if (!('artistId' in value) || value['artistId'] === undefined) return false;
    return true;
}

export function TrackAddRecordFromJSON(json: any): TrackAddRecord {
    return TrackAddRecordFromJSONTyped(json, false);
}

export function TrackAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'durationInSeconds': json['durationInSeconds'],
        'isrc': json['isrc'],
        'artistId': json['artistId'],
    };
}

export function TrackAddRecordToJSON(json: any): TrackAddRecord {
    return TrackAddRecordToJSONTyped(json, false);
}

export function TrackAddRecordToJSONTyped(value?: TrackAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'durationInSeconds': value['durationInSeconds'],
        'isrc': value['isrc'],
        'artistId': value['artistId'],
    };
}

