/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackRecord
 */
export interface TrackRecord {
    /**
     * 
     * @type {string}
     * @memberof TrackRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrackRecord
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof TrackRecord
     */
    durationInSeconds: number;
    /**
     * 
     * @type {string}
     * @memberof TrackRecord
     */
    isrc: string;
    /**
     * 
     * @type {string}
     * @memberof TrackRecord
     */
    artistId: string;
}

/**
 * Check if a given object implements the TrackRecord interface.
 */
export function instanceOfTrackRecord(value: object): value is TrackRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('durationInSeconds' in value) || value['durationInSeconds'] === undefined) return false;
    if (!('isrc' in value) || value['isrc'] === undefined) return false;
    if (!('artistId' in value) || value['artistId'] === undefined) return false;
    return true;
}

export function TrackRecordFromJSON(json: any): TrackRecord {
    return TrackRecordFromJSONTyped(json, false);
}

export function TrackRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'durationInSeconds': json['durationInSeconds'],
        'isrc': json['isrc'],
        'artistId': json['artistId'],
    };
}

export function TrackRecordToJSON(json: any): TrackRecord {
    return TrackRecordToJSONTyped(json, false);
}

export function TrackRecordToJSONTyped(value?: TrackRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'durationInSeconds': value['durationInSeconds'],
        'isrc': value['isrc'],
        'artistId': value['artistId'],
    };
}

