/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';
import type { TrackRecordPagedResponse } from './TrackRecordPagedResponse';
import {
    TrackRecordPagedResponseFromJSON,
    TrackRecordPagedResponseFromJSONTyped,
    TrackRecordPagedResponseToJSON,
    TrackRecordPagedResponseToJSONTyped,
} from './TrackRecordPagedResponse';

/**
 * 
 * @export
 * @interface TrackRecordPagedResponseRequestResponse
 */
export interface TrackRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {TrackRecordPagedResponse}
     * @memberof TrackRecordPagedResponseRequestResponse
     */
    readonly response?: TrackRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TrackRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the TrackRecordPagedResponseRequestResponse interface.
 */
export function instanceOfTrackRecordPagedResponseRequestResponse(value: object): value is TrackRecordPagedResponseRequestResponse {
    return true;
}

export function TrackRecordPagedResponseRequestResponseFromJSON(json: any): TrackRecordPagedResponseRequestResponse {
    return TrackRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function TrackRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : TrackRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TrackRecordPagedResponseRequestResponseToJSON(json: any): TrackRecordPagedResponseRequestResponse {
    return TrackRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function TrackRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<TrackRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

