/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';

/**
 * 
 * @export
 * @interface EventUpdateRecord
 */
export interface EventUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof EventUpdateRecord
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdateRecord
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventUpdateRecord
     */
    location?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EventUpdateRecord
     */
    date?: Date | null;
    /**
     * 
     * @type {UserRecord}
     * @memberof EventUpdateRecord
     */
    artist?: UserRecord | null;
}

/**
 * Check if a given object implements the EventUpdateRecord interface.
 */
export function instanceOfEventUpdateRecord(value: object): value is EventUpdateRecord {
    return true;
}

export function EventUpdateRecordFromJSON(json: any): EventUpdateRecord {
    return EventUpdateRecordFromJSONTyped(json, false);
}

export function EventUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'location': json['location'] == null ? undefined : json['location'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'artist': json['artist'] == null ? undefined : UserRecordFromJSON(json['artist']),
    };
}

export function EventUpdateRecordToJSON(json: any): EventUpdateRecord {
    return EventUpdateRecordToJSONTyped(json, false);
}

export function EventUpdateRecordToJSONTyped(value?: EventUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'location': value['location'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'artist': UserRecordToJSON(value['artist']),
    };
}

