/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventRecord } from './EventRecord';
import {
    EventRecordFromJSON,
    EventRecordFromJSONTyped,
    EventRecordToJSON,
    EventRecordToJSONTyped,
} from './EventRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface EventRecordRequestResponse
 */
export interface EventRecordRequestResponse {
    /**
     * 
     * @type {EventRecord}
     * @memberof EventRecordRequestResponse
     */
    readonly response?: EventRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof EventRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the EventRecordRequestResponse interface.
 */
export function instanceOfEventRecordRequestResponse(value: object): value is EventRecordRequestResponse {
    return true;
}

export function EventRecordRequestResponseFromJSON(json: any): EventRecordRequestResponse {
    return EventRecordRequestResponseFromJSONTyped(json, false);
}

export function EventRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : EventRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function EventRecordRequestResponseToJSON(json: any): EventRecordRequestResponse {
    return EventRecordRequestResponseToJSONTyped(json, false);
}

export function EventRecordRequestResponseToJSONTyped(value?: Omit<EventRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

