/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelUpdateRecord
 */
export interface LabelUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof LabelUpdateRecord
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LabelUpdateRecord
     */
    website?: string | null;
}

/**
 * Check if a given object implements the LabelUpdateRecord interface.
 */
export function instanceOfLabelUpdateRecord(value: object): value is LabelUpdateRecord {
    return true;
}

export function LabelUpdateRecordFromJSON(json: any): LabelUpdateRecord {
    return LabelUpdateRecordFromJSONTyped(json, false);
}

export function LabelUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'website': json['website'] == null ? undefined : json['website'],
    };
}

export function LabelUpdateRecordToJSON(json: any): LabelUpdateRecord {
    return LabelUpdateRecordToJSONTyped(json, false);
}

export function LabelUpdateRecordToJSONTyped(value?: LabelUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'website': value['website'],
    };
}

