/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MerchUpdateRecord
 */
export interface MerchUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof MerchUpdateRecord
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchUpdateRecord
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MerchUpdateRecord
     */
    price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MerchUpdateRecord
     */
    stock?: number | null;
}

/**
 * Check if a given object implements the MerchUpdateRecord interface.
 */
export function instanceOfMerchUpdateRecord(value: object): value is MerchUpdateRecord {
    return true;
}

export function MerchUpdateRecordFromJSON(json: any): MerchUpdateRecord {
    return MerchUpdateRecordFromJSONTyped(json, false);
}

export function MerchUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'stock': json['stock'] == null ? undefined : json['stock'],
    };
}

export function MerchUpdateRecordToJSON(json: any): MerchUpdateRecord {
    return MerchUpdateRecordToJSONTyped(json, false);
}

export function MerchUpdateRecordToJSONTyped(value?: MerchUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'stock': value['stock'],
    };
}

