/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformUpdateRecord
 */
export interface PlatformUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof PlatformUpdateRecord
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlatformUpdateRecord
     */
    url?: string | null;
}

/**
 * Check if a given object implements the PlatformUpdateRecord interface.
 */
export function instanceOfPlatformUpdateRecord(value: object): value is PlatformUpdateRecord {
    return true;
}

export function PlatformUpdateRecordFromJSON(json: any): PlatformUpdateRecord {
    return PlatformUpdateRecordFromJSONTyped(json, false);
}

export function PlatformUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PlatformUpdateRecordToJSON(json: any): PlatformUpdateRecord {
    return PlatformUpdateRecordToJSONTyped(json, false);
}

export function PlatformUpdateRecordToJSONTyped(value?: PlatformUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
    };
}

