/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegisterResponseRecord } from './RegisterResponseRecord';
import {
    RegisterResponseRecordFromJSON,
    RegisterResponseRecordFromJSONTyped,
    RegisterResponseRecordToJSON,
    RegisterResponseRecordToJSONTyped,
} from './RegisterResponseRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RegisterResponseRecordRequestResponse
 */
export interface RegisterResponseRecordRequestResponse {
    /**
     * 
     * @type {RegisterResponseRecord}
     * @memberof RegisterResponseRecordRequestResponse
     */
    readonly response?: RegisterResponseRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RegisterResponseRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the RegisterResponseRecordRequestResponse interface.
 */
export function instanceOfRegisterResponseRecordRequestResponse(value: object): value is RegisterResponseRecordRequestResponse {
    return true;
}

export function RegisterResponseRecordRequestResponseFromJSON(json: any): RegisterResponseRecordRequestResponse {
    return RegisterResponseRecordRequestResponseFromJSONTyped(json, false);
}

export function RegisterResponseRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponseRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : RegisterResponseRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RegisterResponseRecordRequestResponseToJSON(json: any): RegisterResponseRecordRequestResponse {
    return RegisterResponseRecordRequestResponseToJSONTyped(json, false);
}

export function RegisterResponseRecordRequestResponseToJSONTyped(value?: Omit<RegisterResponseRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

