/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterResponseRecord
 */
export interface RegisterResponseRecord {
    /**
     * 
     * @type {string}
     * @memberof RegisterResponseRecord
     */
    message: string;
}

/**
 * Check if a given object implements the RegisterResponseRecord interface.
 */
export function instanceOfRegisterResponseRecord(value: object): value is RegisterResponseRecord {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function RegisterResponseRecordFromJSON(json: any): RegisterResponseRecord {
    return RegisterResponseRecordFromJSONTyped(json, false);
}

export function RegisterResponseRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponseRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function RegisterResponseRecordToJSON(json: any): RegisterResponseRecord {
    return RegisterResponseRecordToJSONTyped(json, false);
}

export function RegisterResponseRecordToJSONTyped(value?: RegisterResponseRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

