/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformRecord } from './PlatformRecord';
import {
    PlatformRecordFromJSON,
    PlatformRecordFromJSONTyped,
    PlatformRecordToJSON,
    PlatformRecordToJSONTyped,
} from './PlatformRecord';
import type { TrackRecord } from './TrackRecord';
import {
    TrackRecordFromJSON,
    TrackRecordFromJSONTyped,
    TrackRecordToJSON,
    TrackRecordToJSONTyped,
} from './TrackRecord';

/**
 * 
 * @export
 * @interface ReleaseAddRecord
 */
export interface ReleaseAddRecord {
    /**
     * 
     * @type {string}
     * @memberof ReleaseAddRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ReleaseAddRecord
     */
    label: string;
    /**
     * 
     * @type {Array<TrackRecord>}
     * @memberof ReleaseAddRecord
     */
    tracks: Array<TrackRecord>;
    /**
     * 
     * @type {Array<PlatformRecord>}
     * @memberof ReleaseAddRecord
     */
    platforms: Array<PlatformRecord>;
}

/**
 * Check if a given object implements the ReleaseAddRecord interface.
 */
export function instanceOfReleaseAddRecord(value: object): value is ReleaseAddRecord {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('tracks' in value) || value['tracks'] === undefined) return false;
    if (!('platforms' in value) || value['platforms'] === undefined) return false;
    return true;
}

export function ReleaseAddRecordFromJSON(json: any): ReleaseAddRecord {
    return ReleaseAddRecordFromJSONTyped(json, false);
}

export function ReleaseAddRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseAddRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'label': json['label'],
        'tracks': ((json['tracks'] as Array<any>).map(TrackRecordFromJSON)),
        'platforms': ((json['platforms'] as Array<any>).map(PlatformRecordFromJSON)),
    };
}

export function ReleaseAddRecordToJSON(json: any): ReleaseAddRecord {
    return ReleaseAddRecordToJSONTyped(json, false);
}

export function ReleaseAddRecordToJSONTyped(value?: ReleaseAddRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'label': value['label'],
        'tracks': ((value['tracks'] as Array<any>).map(TrackRecordToJSON)),
        'platforms': ((value['platforms'] as Array<any>).map(PlatformRecordToJSON)),
    };
}

