/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlatformRecord } from './PlatformRecord';
import {
    PlatformRecordFromJSON,
    PlatformRecordFromJSONTyped,
    PlatformRecordToJSON,
    PlatformRecordToJSONTyped,
} from './PlatformRecord';
import type { TrackRecord } from './TrackRecord';
import {
    TrackRecordFromJSON,
    TrackRecordFromJSONTyped,
    TrackRecordToJSON,
    TrackRecordToJSONTyped,
} from './TrackRecord';

/**
 * 
 * @export
 * @interface ReleaseUpdateRecord
 */
export interface ReleaseUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof ReleaseUpdateRecord
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReleaseUpdateRecord
     */
    label?: string | null;
    /**
     * 
     * @type {Array<TrackRecord>}
     * @memberof ReleaseUpdateRecord
     */
    tracks?: Array<TrackRecord> | null;
    /**
     * 
     * @type {Array<PlatformRecord>}
     * @memberof ReleaseUpdateRecord
     */
    platforms?: Array<PlatformRecord> | null;
}

/**
 * Check if a given object implements the ReleaseUpdateRecord interface.
 */
export function instanceOfReleaseUpdateRecord(value: object): value is ReleaseUpdateRecord {
    return true;
}

export function ReleaseUpdateRecordFromJSON(json: any): ReleaseUpdateRecord {
    return ReleaseUpdateRecordFromJSONTyped(json, false);
}

export function ReleaseUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'label': json['label'] == null ? undefined : json['label'],
        'tracks': json['tracks'] == null ? undefined : ((json['tracks'] as Array<any>).map(TrackRecordFromJSON)),
        'platforms': json['platforms'] == null ? undefined : ((json['platforms'] as Array<any>).map(PlatformRecordFromJSON)),
    };
}

export function ReleaseUpdateRecordToJSON(json: any): ReleaseUpdateRecord {
    return ReleaseUpdateRecordToJSONTyped(json, false);
}

export function ReleaseUpdateRecordToJSONTyped(value?: ReleaseUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'label': value['label'],
        'tracks': value['tracks'] == null ? undefined : ((value['tracks'] as Array<any>).map(TrackRecordToJSON)),
        'platforms': value['platforms'] == null ? undefined : ((value['platforms'] as Array<any>).map(PlatformRecordToJSON)),
    };
}

