/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReleaseRecord } from './ReleaseRecord';
import {
    ReleaseRecordFromJSON,
    ReleaseRecordFromJSONTyped,
    ReleaseRecordToJSON,
    ReleaseRecordToJSONTyped,
} from './ReleaseRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ReleaseRecordRequestResponse
 */
export interface ReleaseRecordRequestResponse {
    /**
     * 
     * @type {ReleaseRecord}
     * @memberof ReleaseRecordRequestResponse
     */
    readonly response?: ReleaseRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ReleaseRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the ReleaseRecordRequestResponse interface.
 */
export function instanceOfReleaseRecordRequestResponse(value: object): value is ReleaseRecordRequestResponse {
    return true;
}

export function ReleaseRecordRequestResponseFromJSON(json: any): ReleaseRecordRequestResponse {
    return ReleaseRecordRequestResponseFromJSONTyped(json, false);
}

export function ReleaseRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : ReleaseRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ReleaseRecordRequestResponseToJSON(json: any): ReleaseRecordRequestResponse {
    return ReleaseRecordRequestResponseToJSONTyped(json, false);
}

export function ReleaseRecordRequestResponseToJSONTyped(value?: Omit<ReleaseRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

