/* tslint:disable */
/* eslint-disable */
/**
 * Distro Kid API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackRecord } from './TrackRecord';
import {
    TrackRecordFromJSON,
    TrackRecordFromJSONTyped,
    TrackRecordToJSON,
    TrackRecordToJSONTyped,
} from './TrackRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface TrackRecordRequestResponse
 */
export interface TrackRecordRequestResponse {
    /**
     * 
     * @type {TrackRecord}
     * @memberof TrackRecordRequestResponse
     */
    readonly response?: TrackRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TrackRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the TrackRecordRequestResponse interface.
 */
export function instanceOfTrackRecordRequestResponse(value: object): value is TrackRecordRequestResponse {
    return true;
}

export function TrackRecordRequestResponseFromJSON(json: any): TrackRecordRequestResponse {
    return TrackRecordRequestResponseFromJSONTyped(json, false);
}

export function TrackRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : TrackRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TrackRecordRequestResponseToJSON(json: any): TrackRecordRequestResponse {
    return TrackRecordRequestResponseToJSONTyped(json, false);
}

export function TrackRecordRequestResponseToJSONTyped(value?: Omit<TrackRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

